"""Contract: the documentation describes this code, not a previous version of it.

Prose cannot be tested, but the things prose gets wrong first can be. Three checks: every
public class and method carries a docstring, every response name the interface reference
mentions is one the code actually reports, and every prose page is reachable from the index.
"""

from __future__ import annotations

import importlib
import importlib.util
import inspect
import json
import pkgutil
import re
import tomllib
from pathlib import Path
from urllib.parse import unquote

import pytest
import yaml

import cdadt
from cdadt import ResponseCatalog

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
BADGES = DOCS / "badges"


#: The published documentation site, which is also where the badge documents are served from.
#: Written out rather than derived because it is what a reader's browser resolves: if the Pages
#: URL ever changes, every endpoint badge silently 404s and this constant is the one place that
#: has to be corrected.
SITE = "https://realjoey.github.io/cdadt/"


def _badge_publisher():
    """Import ``docs/badges/publish_badges.py``, which is a script rather than an installed module."""
    spec = importlib.util.spec_from_file_location("publish_badges", BADGES / "publish_badges.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _pyproject() -> dict:
    """Return the parsed ``pyproject.toml``."""
    with open(ROOT / "pyproject.toml", "rb") as handle:
        return tomllib.load(handle)


def _coverage_report(directory: Path, percent: float) -> Path:
    """Write a minimal ``coverage json`` report claiming *percent*, and return its path.

    Only ``totals.percent_covered`` is written. Fabricating the report rather than running
    coverage is the point: these tests are about what the publisher does with a measurement, and
    a real one would pin them to whatever this suite happens to cover today.
    """
    path = directory / f"coverage-{percent}.json"
    path.write_text(json.dumps({"totals": {"percent_covered": percent}}), encoding="utf-8")
    return path


def _readme_badge_images() -> list[str]:
    """Return the image URL of every badge in the ``README.md`` header, in order.

    Only the run of badges at the top is read. ``README.md`` embeds XDSM diagrams further down
    with the same Markdown image syntax, and those are not status claims about anything.
    """
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    header = readme.split("\n\n", 2)[1]
    return re.findall(r"!\[[^\]]*\]\(([^)]+)\)", header)


#: Members exempt from the docstring requirement, and why.
#:
#: ``__init__`` -- numpydoc documents a constructor in its class's ``Parameters`` section, which
#: is where every one of cdadt's is documented and what the rendered pages show.
#: ``__subclasshook__`` -- generated by :class:`typing.Protocol`, not written by anyone.
EXEMPT_MEMBERS = frozenset({"__init__", "__subclasshook__"})


def _cdadt_modules():
    """Return every module in the cdadt package."""
    modules = [cdadt]
    for info in pkgutil.walk_packages(cdadt.__path__, prefix="cdadt."):
        modules.append(importlib.import_module(info.name))
    return modules


@pytest.mark.contract
def test_every_module_class_and_public_method_has_a_docstring():
    """An undocumented public method is a piece of interface nobody can use from the docs."""
    undocumented = []
    for module in _cdadt_modules():
        if not (module.__doc__ or "").strip():
            undocumented.append(module.__name__)
        for name, obj in vars(module).items():
            if not inspect.isclass(obj) or obj.__module__ != module.__name__:
                continue
            if not (obj.__doc__ or "").strip():
                undocumented.append(f"{module.__name__}.{name}")
            for member_name, member in vars(obj).items():
                if member_name in EXEMPT_MEMBERS:
                    continue
                if member_name.startswith("_") and not member_name.startswith("__"):
                    continue
                if isinstance(member, property):
                    member = member.fget
                elif isinstance(member, staticmethod | classmethod):
                    member = member.__func__
                if not inspect.isfunction(member):
                    continue
                if not (member.__doc__ or "").strip():
                    undocumented.append(f"{module.__name__}.{name}.{member_name}")

    assert not undocumented, "These have no docstring:\n  " + "\n  ".join(undocumented)


@pytest.mark.contract
def test_every_response_named_in_the_interface_reference_exists():
    """The one page that lists responses by name must list ones the code reports."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")

    # Response names appear in the table as ``double-backtick`` literals in the second column.
    quoted = set(re.findall(r"``([A-Za-z][A-Za-z0-9_]*)``", text))
    # Only check the ones that look like response names rather than YAML keys or code.
    candidates = {name for name in quoted if name in catalog or name.endswith(("_weight", "_fuel", "_area"))}

    missing = sorted(name for name in candidates if name not in catalog)
    assert not missing, f"interface.rst names responses that no discipline reports: {missing}"


@pytest.mark.contract
def test_every_response_path_named_in_the_interface_reference_is_the_real_one():
    """A path transcribed by hand is a path that silently goes stale."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")
    real_paths = {catalog.response(name).path for name in catalog}

    quoted = set(re.findall(r"``([a-zA-Z_][\w|.]*\.[\w|]+)``", text))
    # A quoted dotted string is a path claim only if it looks like one of ours.
    claimed = {p for p in quoted if p.startswith(("mission.", "empty_weight.", "tail_lever_arm"))}

    wrong = sorted(claimed - real_paths)
    assert not wrong, f"interface.rst names paths no response reads: {wrong}"


@pytest.mark.contract
def test_every_prose_page_is_reachable_from_the_index():
    """A page nobody links to is a page nobody reads and nobody maintains."""
    index = (DOCS / "index.rst").read_text(encoding="utf-8")
    pages = {path.stem for path in DOCS.glob("*.rst")} - {"index"}
    unlinked = sorted(page for page in pages if page not in index)
    assert not unlinked, f"These pages are not in the index toctree: {unlinked}"


#: How the case table in ``README.md`` describes each aerodynamics, and the class that description
#: must correspond to. ``None`` means the case names no loads model at all, because it drives
#: OpenConcept's own analysis group.
AERODYNAMICS_DESCRIPTIONS = {
    "OpenConcept's own": None,
    "cdadt group, polar": "cdadt.models.polar:PolarLoads",
    "openavl": "cdadt.adapter.avl:OpenAVLLoads",
    "OpenAeroStruct": "cdadt.adapter.oas:OpenAeroStructLoads",
}


@pytest.mark.contract
def test_the_case_table_describes_the_case_files_that_exist():
    """Prose that names a case file must describe the case file it names.

    This is the one class of documentation error nothing here was catching, and it went out in a
    push. ``README.md`` stated that a case *"flies the same aeroplane and the same mission with a
    vortex lattice built on its wing"* while that file set
    ``aerodynamic_loads: cdadt.models.polar:PolarLoads`` -- a parabolic polar, with the lattice
    lines commented out directly above it. Every other check here passed: the numbers were anchored,
    the response names were real, the page was reachable. None of them reads a case file.

    So this one does. For every row of the table, the aerodynamics named in the prose and the wave
    drag it claims are compared against what the YAML actually sets.
    """
    table = re.findall(
        r"^\| `(b738[a-z_]*\.yaml)` \| ([^|]+?) \| ([^|]+?) \|", (ROOT / "README.md").read_text(encoding="utf-8"), re.M
    )
    assert len(table) == 3, f"the case table should list the three sizing cases; found {len(table)}"

    mismatches = []
    for name, described, wave_claimed in table:
        case = ROOT / "cases" / name
        if not case.is_file():
            mismatches.append(f"{name}: named in the table, absent from cases/")
            continue
        settings = "\n".join(line.split("#")[0] for line in case.read_text(encoding="utf-8").splitlines())

        expected = AERODYNAMICS_DESCRIPTIONS.get(described.strip())
        actual = re.search(r"^    aerodynamic_loads: (\S+)", settings, re.M)
        actual = actual.group(1) if actual else None
        if expected != actual:
            mismatches.append(f"{name}: table says {described.strip()!r}, file sets {actual}")

        wave = re.search(r"^    wave_drag: (\S+)", settings, re.M)
        wave = wave.group(1) if wave else None
        claimed = wave_claimed.strip()
        truth = {"on": "true", "off": "false", "none possible": None}.get(claimed, "?")
        if truth != wave:
            mismatches.append(f"{name}: table claims wave drag {claimed!r}, file sets {wave}")

    assert not mismatches, "the documented case table does not match the case files:\n  " + "\n  ".join(mismatches)


@pytest.mark.contract
def test_every_case_file_appears_in_the_documentation():
    """A case nobody documents is one nobody knows the purpose of, which is how duplicates happen.

    One did: a case file that had become byte-for-byte identical to another once a default changed,
    and nothing noticed because neither was described anywhere.
    """
    documented = set()
    for page in (ROOT / "README.md", *sorted(DOCS.glob("*.rst"))):
        documented |= set(re.findall(r"(b738[a-z_]*\.yaml)", page.read_text(encoding="utf-8")))

    present = {path.name for path in (ROOT / "cases").glob("*.yaml")}
    assert not present - documented, f"case files nothing documents: {sorted(present - documented)}"
    assert not documented - present, f"documentation names case files that do not exist: {sorted(documented - present)}"


# =============================================================================================
# The README badges
#
# Every badge is live. Nothing is committed: shields.io fetches each value from the source that
# defines it -- GitHub for the CI status and the licence, raw.githubusercontent for the Python
# floor, and the published documentation site for the two that only a run can know, coverage and
# version. See docs/badges/publish_badges.py for why those two are emitted by CI rather than
# stored.
#
# Live does not mean self-checking. A badge URL can point at a file that was renamed, a TOML key
# that no longer exists, or a site path CI does not write, and shields.io renders every one of
# those as a small grey error that reads like a rendering glitch. These tests are what turn that
# into a failing gate, offline -- nothing here reaches the network.
# =============================================================================================


@pytest.mark.contract
def test_every_readme_badge_resolves_to_a_source_this_repository_controls():
    """Each badge is traced back to the thing that supplies its value, by hand and offline.

    The check is deliberately exhaustive rather than a lookup of known-good URLs: an
    unrecognised badge shape *fails*. Adding a badge therefore means saying here what makes it
    true, which is the whole reason the old committed badges were tested at all.
    """
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    project = _pyproject()
    badges = _readme_badge_images()

    assert len(badges) >= 7, f"README shows only {len(badges)} badges; the header run was not parsed"

    unrecognised = []
    for url in badges:
        decoded = unquote(url)

        if "/actions/workflows/" in decoded:
            # GitHub serves this by *filename*; a renamed workflow 404s rather than going red.
            name = re.search(r"actions/workflows/([\w.-]+)/badge\.svg", decoded).group(1)
            assert (ROOT / ".github" / "workflows" / name).is_file(), f"the CI badge names {name}, which is gone"

        elif decoded.startswith("https://img.shields.io/endpoint?url=" + SITE + "badges/"):
            # Served from our own site. That it is *written and published* is the next test's
            # subject; what has to hold here is only that a step exists to write it at all.
            assert "publish_badges.py" in workflow, "no step writes the endpoint documents this badge reads"

        elif decoded.startswith("https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/"):
            # ruff publishes this document itself; what has to hold here is that we use ruff.
            assert "ruff" in " ".join(project["project"]["optional-dependencies"]["dev"])

        elif decoded.startswith("https://img.shields.io/badge/dynamic/toml"):
            # The JSONPath has to resolve in the file the badge names, or shields renders an error.
            assert "pyproject.toml" in decoded, "a dynamic/toml badge that does not read pyproject.toml"
            key = re.search(r'query=\$\.project\["([^"]+)"\]', decoded).group(1)
            assert key in project["project"], f"the python badge queries project.{key}, which is not declared"

        elif decoded.startswith("https://img.shields.io/github/license/"):
            assert (ROOT / project["project"]["license"]["file"]).is_file()

        elif decoded.startswith("https://img.shields.io/website?url=" + SITE):
            # The docs badge reports whether the site is reachable, so it must name the real site.
            assert "publish" in workflow.lower() or "deploy-pages" in workflow

        # Note the space: `decoded` has been through unquote, so the URL's %20 is gone by here.
        elif decoded.startswith("https://img.shields.io/badge/code style-black-"):
            assert "black" in " ".join(project["project"]["optional-dependencies"]["dev"])

        else:
            unrecognised.append(url)

    assert not unrecognised, "these badges name no source this test knows how to verify:\n  " + "\n  ".join(
        unrecognised
    )


@pytest.mark.contract
def test_the_workflow_publishes_the_badge_documents_the_readme_reads(tmp_path: Path):
    """The badge URL and the file CI writes are two halves of one contract, kept in two files.

    They are edited independently and nothing but this test connects them: rename an output or
    move the directory and every endpoint badge 404s, on a site that is otherwise perfectly fine.
    So the publisher is actually *run* here and its filenames compared against the URLs.
    """
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    wanted = {
        decoded.rsplit("/", 1)[-1]
        for decoded in map(unquote, _readme_badge_images())
        if decoded.startswith("https://img.shields.io/endpoint?url=" + SITE + "badges/")
    }

    assert wanted, "README reads no endpoint badge from our own site; nothing publishes a measured value"

    written = {path.name for path in _badge_publisher().write(_coverage_report(tmp_path, 100.0), tmp_path / "out")}
    assert wanted <= written, f"README reads badge documents CI never writes: {sorted(wanted - written)}"

    # The two ends of the path the URLs assume: `full` hands the documents over, and `pages`
    # unpacks them under <site>/badges/.
    assert "name: badges" in workflow, "`full` does not hand its badge documents to the `pages` job"
    assert "path: site/badges" in workflow, "the `pages` job does not place the documents under <site>/badges/"


@pytest.mark.contract
def test_the_reference_case_frees_nothing_and_so_can_have_nothing_on_a_bound():
    """The reference analysis has no design variables and no bounds, and the prose says so.

    Written because the documentation invited a real misreading. A comparison table headed
    ``reference | openavl | OpenAeroStruct`` listed quarter-chord sweep as "15.0 -- lower bound"
    in the first column, and "reference" there meant *the reference aerodynamics, optimized*
    while every other use of the word in these pages means *OpenConcept's own analysis*. Read the
    second way -- which is the natural way -- it says the reference example pins sweep to a bound,
    and OpenConcept's example has no bounds to pin anything to.

    The numbers were right and the label was wrong, which is the harder kind of error to see. So
    the claim that replaced it is checked here: the reference case frees nothing, and therefore
    nothing in it can sit on a bound. If a future case file gives ``b738.yaml`` an ``optimize:``
    entry, the pages that say otherwise fail with it.
    """
    reference = yaml.safe_load((ROOT / "cases" / "b738.yaml").read_text(encoding="utf-8"))
    variables = reference["design_variables"]

    freed = sorted(name for name, spec in variables.items() if isinstance(spec, dict) and "optimize" in spec)
    assert not freed, (
        "cases/b738.yaml is documented as the reference analysis, with no design variables and no "
        f"bounds; these are freed: {freed}"
    )

    # The specific number the prose quotes, from the file rather than from memory.
    assert variables["ac|geom|wing|c4sweep"]["value"] == 25
    assert variables["ac|geom|wing|c4sweep"]["units"] == "deg"


@pytest.mark.contract
def test_the_workflow_runs_every_gate_this_project_claims_to_enforce():
    """CI must run the same four gates as a developer, or the badge stands for a subset.

    This is the failure worth guarding: a workflow trimmed to keep the runner cheap still shows
    the same green tick, and the tick is then evidence for less than it appears to be. Naming
    each gate here means dropping one has to be done deliberately, in the open.
    """
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    missing = [
        gate
        for gate, command in {
            "black": "black --check .",
            "ruff": "ruff check .",
            "the test suite": "coverage run -m pytest",
            "the coverage threshold": "coverage report",
            "the documentation build": "sphinx -W",
        }.items()
        if command not in workflow
    ]
    assert not missing, f"the workflow no longer runs: {missing}"


@pytest.mark.contract
def test_the_published_badge_documents_say_what_this_project_declares(tmp_path: Path):
    """What CI would publish, re-derived here from the sources rather than from the publisher.

    Deliberately not by calling the publisher twice and comparing -- that would only establish
    that it agrees with itself. The version is *imported* here and *imported* there, but the
    coverage figure is checked against a report this test fabricates, so the number on the badge
    is traced to a measurement rather than to a constant.
    """
    publisher = _badge_publisher()

    version = json.loads((publisher.write(_coverage_report(tmp_path, 100.0), tmp_path / "out")[1]).read_text())
    assert version["schemaVersion"] == 1, "shields.io rejects an endpoint document of an unknown schema version"
    assert version["label"] == "version"
    assert version["message"] == cdadt.__version__

    coverage = json.loads((tmp_path / "out" / "coverage.json").read_text())
    assert coverage["message"] == "100%"
    assert coverage["color"] == "brightgreen"


@pytest.mark.contract
def test_a_coverage_short_of_total_cannot_render_as_total(tmp_path: Path):
    """The one way this badge could lie: rounding 99.96 up into a claim of complete coverage.

    ``fail_under = 100`` means a published badge should always read 100%, so this case cannot
    arise while the gate holds -- which is exactly why it needs a test. The gate is the thing
    that would have to fail first, and on the day it does the badge must not cover for it.
    """
    publisher = _badge_publisher()

    for measured, expected in ((99.96, "99.9%"), (99.0, "99.0%"), (100.0, "100%")):
        publisher.write(_coverage_report(tmp_path, measured), tmp_path / str(measured))
        rendered = json.loads((tmp_path / str(measured) / "coverage.json").read_text())["message"]
        assert rendered == expected, f"{measured}% coverage rendered as {rendered}"


@pytest.mark.contract
def test_the_coverage_gate_this_badge_stands_on_is_total():
    """The badge reports a measurement; this is the gate that makes the measurement mean something.

    Without it the threshold could be quietly lowered and the badge would faithfully report
    whatever the smaller suite achieved -- honest, and no longer the claim it was put there to
    make.
    """
    assert (
        _pyproject()["tool"]["coverage"]["report"]["fail_under"] == 100
    ), "the coverage badge is displayed on the strength of this gate being total"
