"""Contract: the documentation describes this code, not a previous version of it.

Prose cannot be tested, but the things prose gets wrong first can be. Three checks: every
public class and method carries a docstring, every response name the interface reference
mentions is one the code actually reports, and every prose page is reachable from the index.
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
import re
from pathlib import Path

import pytest

import cdadt
from cdadt import ResponseCatalog

DOCS = Path(__file__).resolve().parent.parent / "docs"

#: Members exempt from the docstring requirement, and why.
#:
#: ``__init__`` -- numpydoc documents a constructor in its class's ``Parameters`` section, which
#: is where every one of cdadt's is documented and what the rendered pages show.
#: ``__subclasshook__`` -- generated by :class:`typing.Protocol`, not written by anyone.
EXEMPT_MEMBERS = frozenset({"__init__", "__subclasshook__"})


def _cdadt_modules():
    """Return every module in the cdadt package."""
    modules = [cdadt]
    for info in pkgutil.walk_packages(cdadt.__path__, prefix="cdadt."):
        modules.append(importlib.import_module(info.name))
    return modules


@pytest.mark.contract
def test_every_module_class_and_public_method_has_a_docstring():
    """An undocumented public method is a piece of interface nobody can use from the docs."""
    undocumented = []
    for module in _cdadt_modules():
        if not (module.__doc__ or "").strip():
            undocumented.append(module.__name__)
        for name, obj in vars(module).items():
            if not inspect.isclass(obj) or obj.__module__ != module.__name__:
                continue
            if not (obj.__doc__ or "").strip():
                undocumented.append(f"{module.__name__}.{name}")
            for member_name, member in vars(obj).items():
                if member_name in EXEMPT_MEMBERS:
                    continue
                if member_name.startswith("_") and not member_name.startswith("__"):
                    continue
                if isinstance(member, property):
                    member = member.fget
                elif isinstance(member, staticmethod | classmethod):
                    member = member.__func__
                if not inspect.isfunction(member):
                    continue
                if not (member.__doc__ or "").strip():
                    undocumented.append(f"{module.__name__}.{name}.{member_name}")

    assert not undocumented, "These have no docstring:\n  " + "\n  ".join(undocumented)


@pytest.mark.contract
def test_every_response_named_in_the_interface_reference_exists():
    """The one page that lists responses by name must list ones the code reports."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")

    # Response names appear in the table as ``double-backtick`` literals in the second column.
    quoted = set(re.findall(r"``([A-Za-z][A-Za-z0-9_]*)``", text))
    # Only check the ones that look like response names rather than YAML keys or code.
    candidates = {name for name in quoted if name in catalog or name.endswith(("_weight", "_fuel", "_area"))}

    missing = sorted(name for name in candidates if name not in catalog)
    assert not missing, f"interface.rst names responses that no discipline reports: {missing}"


@pytest.mark.contract
def test_every_response_path_named_in_the_interface_reference_is_the_real_one():
    """A path transcribed by hand is a path that silently goes stale."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")
    real_paths = {catalog.response(name).path for name in catalog}

    quoted = set(re.findall(r"``([a-zA-Z_][\w|.]*\.[\w|]+)``", text))
    # A quoted dotted string is a path claim only if it looks like one of ours.
    claimed = {p for p in quoted if p.startswith(("mission.", "empty_weight.", "tail_lever_arm"))}

    wrong = sorted(claimed - real_paths)
    assert not wrong, f"interface.rst names paths no response reads: {wrong}"


@pytest.mark.contract
def test_every_prose_page_is_reachable_from_the_index():
    """A page nobody links to is a page nobody reads and nobody maintains."""
    index = (DOCS / "index.rst").read_text(encoding="utf-8")
    pages = {path.stem for path in DOCS.glob("*.rst")} - {"index"}
    unlinked = sorted(page for page in pages if page not in index)
    assert not unlinked, f"These pages are not in the index toctree: {unlinked}"
