"""Contract: the documentation describes this code, not a previous version of it.

Prose cannot be tested, but the things prose gets wrong first can be. Three checks: every
public class and method carries a docstring, every response name the interface reference
mentions is one the code actually reports, and every prose page is reachable from the index.
"""

from __future__ import annotations

import importlib
import importlib.util
import inspect
import pkgutil
import re
import tomllib
from pathlib import Path

import pytest
import yaml

import cdadt
from cdadt import ResponseCatalog

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
BADGES = DOCS / "badges"


def _badge_builder():
    """Import ``docs/badges/build_badges.py``, which is a script rather than an installed module."""
    spec = importlib.util.spec_from_file_location("build_badges", BADGES / "build_badges.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _pyproject() -> dict:
    """Return the parsed ``pyproject.toml``."""
    with open(ROOT / "pyproject.toml", "rb") as handle:
        return tomllib.load(handle)


def _badge_value(name: str) -> str:
    """Return what the committed badge ``name`` claims, read out of its own ``<title>``."""
    title = re.search(r"<title>[^:]+: ([^<]+)</title>", (BADGES / f"{name}.svg").read_text(encoding="utf-8"))
    assert title, f"docs/badges/{name}.svg has no <title>, so nothing can check what it claims"
    return title.group(1)


#: Members exempt from the docstring requirement, and why.
#:
#: ``__init__`` -- numpydoc documents a constructor in its class's ``Parameters`` section, which
#: is where every one of cdadt's is documented and what the rendered pages show.
#: ``__subclasshook__`` -- generated by :class:`typing.Protocol`, not written by anyone.
EXEMPT_MEMBERS = frozenset({"__init__", "__subclasshook__"})


def _cdadt_modules():
    """Return every module in the cdadt package."""
    modules = [cdadt]
    for info in pkgutil.walk_packages(cdadt.__path__, prefix="cdadt."):
        modules.append(importlib.import_module(info.name))
    return modules


@pytest.mark.contract
def test_every_module_class_and_public_method_has_a_docstring():
    """An undocumented public method is a piece of interface nobody can use from the docs."""
    undocumented = []
    for module in _cdadt_modules():
        if not (module.__doc__ or "").strip():
            undocumented.append(module.__name__)
        for name, obj in vars(module).items():
            if not inspect.isclass(obj) or obj.__module__ != module.__name__:
                continue
            if not (obj.__doc__ or "").strip():
                undocumented.append(f"{module.__name__}.{name}")
            for member_name, member in vars(obj).items():
                if member_name in EXEMPT_MEMBERS:
                    continue
                if member_name.startswith("_") and not member_name.startswith("__"):
                    continue
                if isinstance(member, property):
                    member = member.fget
                elif isinstance(member, staticmethod | classmethod):
                    member = member.__func__
                if not inspect.isfunction(member):
                    continue
                if not (member.__doc__ or "").strip():
                    undocumented.append(f"{module.__name__}.{name}.{member_name}")

    assert not undocumented, "These have no docstring:\n  " + "\n  ".join(undocumented)


@pytest.mark.contract
def test_every_response_named_in_the_interface_reference_exists():
    """The one page that lists responses by name must list ones the code reports."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")

    # Response names appear in the table as ``double-backtick`` literals in the second column.
    quoted = set(re.findall(r"``([A-Za-z][A-Za-z0-9_]*)``", text))
    # Only check the ones that look like response names rather than YAML keys or code.
    candidates = {name for name in quoted if name in catalog or name.endswith(("_weight", "_fuel", "_area"))}

    missing = sorted(name for name in candidates if name not in catalog)
    assert not missing, f"interface.rst names responses that no discipline reports: {missing}"


@pytest.mark.contract
def test_every_response_path_named_in_the_interface_reference_is_the_real_one():
    """A path transcribed by hand is a path that silently goes stale."""
    catalog = ResponseCatalog()
    text = (DOCS / "interface.rst").read_text(encoding="utf-8")
    real_paths = {catalog.response(name).path for name in catalog}

    quoted = set(re.findall(r"``([a-zA-Z_][\w|.]*\.[\w|]+)``", text))
    # A quoted dotted string is a path claim only if it looks like one of ours.
    claimed = {p for p in quoted if p.startswith(("mission.", "empty_weight.", "tail_lever_arm"))}

    wrong = sorted(claimed - real_paths)
    assert not wrong, f"interface.rst names paths no response reads: {wrong}"


@pytest.mark.contract
def test_every_prose_page_is_reachable_from_the_index():
    """A page nobody links to is a page nobody reads and nobody maintains."""
    index = (DOCS / "index.rst").read_text(encoding="utf-8")
    pages = {path.stem for path in DOCS.glob("*.rst")} - {"index"}
    unlinked = sorted(page for page in pages if page not in index)
    assert not unlinked, f"These pages are not in the index toctree: {unlinked}"


#: How the case table in ``README.md`` describes each aerodynamics, and the class that description
#: must correspond to. ``None`` means the case names no loads model at all, because it drives
#: OpenConcept's own analysis group.
AERODYNAMICS_DESCRIPTIONS = {
    "OpenConcept's own": None,
    "cdadt group, polar": "cdadt.models.polar:PolarLoads",
    "openavl": "cdadt.adapter.avl:OpenAVLLoads",
    "OpenAeroStruct": "cdadt.adapter.oas:OpenAeroStructLoads",
}


@pytest.mark.contract
def test_the_case_table_describes_the_case_files_that_exist():
    """Prose that names a case file must describe the case file it names.

    This is the one class of documentation error nothing here was catching, and it went out in a
    push. ``README.md`` stated that a case *"flies the same aeroplane and the same mission with a
    vortex lattice built on its wing"* while that file set
    ``aerodynamic_loads: cdadt.models.polar:PolarLoads`` -- a parabolic polar, with the lattice
    lines commented out directly above it. Every other check here passed: the numbers were anchored,
    the response names were real, the page was reachable. None of them reads a case file.

    So this one does. For every row of the table, the aerodynamics named in the prose and the wave
    drag it claims are compared against what the YAML actually sets.
    """
    table = re.findall(
        r"^\| `(b738[a-z_]*\.yaml)` \| ([^|]+?) \| ([^|]+?) \|", (ROOT / "README.md").read_text(encoding="utf-8"), re.M
    )
    assert len(table) == 3, f"the case table should list the three sizing cases; found {len(table)}"

    mismatches = []
    for name, described, wave_claimed in table:
        case = ROOT / "cases" / name
        if not case.is_file():
            mismatches.append(f"{name}: named in the table, absent from cases/")
            continue
        settings = "\n".join(line.split("#")[0] for line in case.read_text(encoding="utf-8").splitlines())

        expected = AERODYNAMICS_DESCRIPTIONS.get(described.strip())
        actual = re.search(r"^    aerodynamic_loads: (\S+)", settings, re.M)
        actual = actual.group(1) if actual else None
        if expected != actual:
            mismatches.append(f"{name}: table says {described.strip()!r}, file sets {actual}")

        wave = re.search(r"^    wave_drag: (\S+)", settings, re.M)
        wave = wave.group(1) if wave else None
        claimed = wave_claimed.strip()
        truth = {"on": "true", "off": "false", "none possible": None}.get(claimed, "?")
        if truth != wave:
            mismatches.append(f"{name}: table claims wave drag {claimed!r}, file sets {wave}")

    assert not mismatches, "the documented case table does not match the case files:\n  " + "\n  ".join(mismatches)


@pytest.mark.contract
def test_every_case_file_appears_in_the_documentation():
    """A case nobody documents is one nobody knows the purpose of, which is how duplicates happen.

    One did: a case file that had become byte-for-byte identical to another once a default changed,
    and nothing noticed because neither was described anywhere.
    """
    documented = set()
    for page in (ROOT / "README.md", *sorted(DOCS.glob("*.rst"))):
        documented |= set(re.findall(r"(b738[a-z_]*\.yaml)", page.read_text(encoding="utf-8")))

    present = {path.name for path in (ROOT / "cases").glob("*.yaml")}
    assert not present - documented, f"case files nothing documents: {sorted(present - documented)}"
    assert not documented - present, f"documentation names case files that do not exist: {sorted(documented - present)}"


# =============================================================================================
# The README badges
#
# cdadt is a private repository, so the badges cannot be shields.io URLs -- an anonymous service
# cannot read a private repo. They are generated by docs/badges/build_badges.py and committed,
# which trades a live status for a stored one. A stored status is a claim, and an unchecked claim
# is decoration, so these tests are what make the badges worth displaying.
# =============================================================================================


@pytest.mark.contract
def test_every_committed_badge_is_shown_and_every_shown_badge_exists():
    """A badge nobody displays is dead weight; a displayed badge that is missing is a broken image."""
    shown = set(
        re.findall(r"!\[[^\]]*\]\(docs/badges/([a-z_]+)\.svg\)", (ROOT / "README.md").read_text(encoding="utf-8"))
    )
    committed = {path.stem for path in BADGES.glob("*.svg")}

    assert not committed - shown, f"badges generated but not displayed: {sorted(committed - shown)}"
    assert not shown - committed, f"README shows badges that do not exist: {sorted(shown - committed)}"


@pytest.mark.contract
def test_the_reference_case_frees_nothing_and_so_can_have_nothing_on_a_bound():
    """The reference analysis has no design variables and no bounds, and the prose says so.

    Written because the documentation invited a real misreading. A comparison table headed
    ``reference | openavl | OpenAeroStruct`` listed quarter-chord sweep as "15.0 -- lower bound"
    in the first column, and "reference" there meant *the reference aerodynamics, optimized*
    while every other use of the word in these pages means *OpenConcept's own analysis*. Read the
    second way -- which is the natural way -- it says the reference example pins sweep to a bound,
    and OpenConcept's example has no bounds to pin anything to.

    The numbers were right and the label was wrong, which is the harder kind of error to see. So
    the claim that replaced it is checked here: the reference case frees nothing, and therefore
    nothing in it can sit on a bound. If a future case file gives ``b738.yaml`` an ``optimize:``
    entry, the pages that say otherwise fail with it.
    """
    reference = yaml.safe_load((ROOT / "cases" / "b738.yaml").read_text(encoding="utf-8"))
    variables = reference["design_variables"]

    freed = sorted(name for name, spec in variables.items() if isinstance(spec, dict) and "optimize" in spec)
    assert not freed, (
        "cases/b738.yaml is documented as the reference analysis, with no design variables and no "
        f"bounds; these are freed: {freed}"
    )

    # The specific number the prose quotes, from the file rather than from memory.
    assert variables["ac|geom|wing|c4sweep"]["value"] == 25
    assert variables["ac|geom|wing|c4sweep"]["units"] == "deg"


@pytest.mark.contract
def test_the_ci_badge_points_at_a_workflow_that_exists():
    """The one live badge names a workflow file, and a renamed workflow would silently break it.

    GitHub serves ``.../actions/workflows/<file>/badge.svg`` by *filename*. Rename the workflow
    file and the badge does not go red -- it 404s, and a broken image beside seven healthy ones
    reads as a rendering glitch rather than as a missing gate.
    """
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    referenced = re.findall(r"actions/workflows/([\w.-]+)/badge\.svg", readme)

    assert referenced, "README shows no CI badge; the test status is then nothing but an assertion"
    for name in set(referenced):
        assert (
            ROOT / ".github" / "workflows" / name
        ).is_file(), f"the CI badge names .github/workflows/{name}, which does not exist"


@pytest.mark.contract
def test_the_workflow_runs_every_gate_this_project_claims_to_enforce():
    """CI must run the same four gates as a developer, or the badge stands for a subset.

    This is the failure worth guarding: a workflow trimmed to keep the runner cheap still shows
    the same green tick, and the tick is then evidence for less than it appears to be. Naming
    each gate here means dropping one has to be done deliberately, in the open.
    """
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    missing = [
        gate
        for gate, command in {
            "black": "black --check .",
            "ruff": "ruff check .",
            "the test suite": "coverage run -m pytest",
            "the coverage threshold": "coverage report",
            "the documentation build": "sphinx -W",
        }.items()
        if command not in workflow
    ]
    assert not missing, f"the workflow no longer runs: {missing}"


@pytest.mark.contract
def test_each_badge_states_what_the_project_actually_declares():
    """The four derived badges are re-derived here, from the sources rather than from the builder.

    Deliberately not by calling :mod:`build_badges` and comparing -- that would only establish
    that the builder agrees with itself. Each value is read again from the file that defines it,
    by a different route where one exists: the version is *imported* here and *parsed* there.
    """
    project = _pyproject()

    assert _badge_value("version") == cdadt.__version__
    assert _badge_value("python") == project["project"]["requires-python"].lstrip(">=") + "+"

    licence_file = ROOT / project["project"]["license"]["file"]
    assert _badge_value("license") == licence_file.read_text(encoding="utf-8").splitlines()[0].strip().removesuffix(
        " License"
    )


@pytest.mark.contract
def test_the_coverage_badge_reports_the_threshold_the_suite_enforces():
    """The coverage badge is a gate setting, not a remembered measurement.

    This is the badge that would be easiest to fake, so it is wired to the one number that cannot
    be wrong while the suite passes: ``fail_under``. ``coverage report`` exits non-zero below it,
    so a green suite *is* the evidence for whatever this badge says.

    The second assertion locks the threshold at 100. Without it the gate could be quietly lowered
    and the badge would faithfully regenerate to match -- honest, but no longer the claim the
    badge was put there to make.
    """
    threshold = _pyproject()["tool"]["coverage"]["report"]["fail_under"]

    assert _badge_value("coverage") == f"{threshold}%"
    assert threshold == 100, "the coverage badge is displayed on the strength of this gate being total"


@pytest.mark.contract
def test_the_toolchain_badges_name_tools_the_project_actually_uses():
    """``code style: black`` is a claim about the environment, and environments drift."""
    extras = _pyproject()["project"]["optional-dependencies"]

    assert _badge_value("code_style") in extras["dev"]
    assert _badge_value("linting") in extras["dev"]
    assert _badge_value("docs") in extras["docs"]


@pytest.mark.contract
def test_the_committed_badges_are_what_the_builder_produces_today(tmp_path: Path):
    """Regenerate every badge and compare bytes, so a stale or hand-edited SVG fails here.

    The value checks above say *what* is wrong when a source changes. This one says *that*
    something is wrong for any reason at all -- including someone editing an SVG directly, which
    is the one way a badge could claim something no source ever said.
    """
    builder = _badge_builder()
    builder.BadgeSet(directory=tmp_path).write()

    stale = [
        path.name
        for path in sorted(tmp_path.glob("*.svg"))
        if (BADGES / path.name).read_text(encoding="utf-8") != path.read_text(encoding="utf-8")
    ]
    assert not stale, "these badges are out of date; run `python docs/badges/build_badges.py`:\n  " + "\n  ".join(stale)
